# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6118954e688602fcf1d19ad8dca0e37f1b0755d4a9acdd3e4ee0176b66fb2c7214f23000250dbf87f06f9991aa71e4c251ac68cea063b10eb14820eb6b05d4f6

test:
  secret_key_base: 358ad246be1c2d28acaa855825f1f8f8b55e5225cf4df1e73192b9c527876fd9b16aec4695e59fa96838b2eb2e2be5d59f474e5c125dcca6bdf0b9473c28a60a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
